Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

choco install chocolateygui -y
choco install vscode -y
choco install git -y
choco install putty.install -y
choco install curl -y
choco install python -y
choco install dotnetcore-sdk -y
choco install nodejs -y
choco install notepadplusplus -y
choco install microsoft-windows-terminal -y
choco install cascadiamonopl -y
choco install cascadiacodepl -y
choco install calibre -y
choco install carnac -y
choco install microsoft-edge -y
choco install googlechrome -y
choco install cura-new -y
choco install obs -y
choco install obs-ndi -y
choco install vlc -y
choco install airserver -y
choco install sysinternals -y
choco install autoruns -y
choco install powertoys -y
choco install zoomit -y
choco install autohotkey.portable -y
choco install cygwin -y
choco install zoom -y
choco install spotify -y 
choco install adobereader -y